sudo: disabled
language: python
dist: bionic
python:
  - "3.5"
  - "3.7"
install: 
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# The fx script is not tested as it needs API key
script:
  - coverage run --append ./bitstamp_ config
  - coverage run --append ./conseq_ config
  - coverage run --append ./czk_ config
  - coverage run --append ./ing_ config
  - coverage run --append ./partners_ config
  - coverage run --append ./pse_ config
  - coverage run --append ./bitstamp_
  - coverage run --append ./conseq_
  - coverage run --append ./czk_
  - coverage run --append ./ing_
  - coverage run --append ./partners_
  - coverage run --append ./pse_
after_script:
  - codecov
