sudo: disabled
language: python
python:
  - "3.6"
install: 
  - pip install -r requirements.txt
# The fx script is not tested as it needs API key
script:
  - ./bitstamp_
  - ./conseq_
  - ./czk_
  - ./ing_
  - ./partners_
  - ./pse_
