#!/usr/bin/env python3
import json
import os.path
import sys
from urllib.request import Request, urlopen

BASE = "https://api.bitfinex.com/v2/ticker/t{0}"
# /ticker/tBTCUSD

TICKER = os.path.basename(sys.argv[0]).replace("bfx_", "").upper()
if not TICKER:
    TICKER = "BTCUSD"

NAMES = {
    "BTC": "Bitcoin",
    "BTG": "Bitcoin Gold",
    "BCH": "Bitcoin Cash",
    "LTC": "Litecoin",
    "USDT": "USD",
    "EUR": "EUR",
    "XRP": "Ripple",
    "ETH": "Ethereum",
    "DSH": "Dash",
    "ZEC": "Zcash",
}

VSOURCE = SOURCE = TICKER[:3]
VTARGET = TARGET = TICKER[3:]

if SOURCE in NAMES:
    VSOURCE = NAMES[SOURCE]
if TARGET in NAMES:
    VTARGET = NAMES[TARGET]

try:
    CMD = sys.argv[1]
except IndexError:
    CMD = "fetch"

if CMD == "config":
    print("host_name ticker")
    print("graph_title Bitfinex: {0} / {1}".format(VSOURCE, VTARGET))
    print("graph_args --base 1000")
    print("graph_scale no")
    print("graph_category ticker")
    print("graph_vlabel {0}".format(TARGET))
    print("{0}.label {1}/{2}".format(TICKER.lower(), SOURCE, TARGET))
else:
    request = Request(
        BASE.format(TICKER),
        data=None,
        headers={
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36"
        },
    )
    with urlopen(request) as handle:
        payload = handle.read().decode("utf-8")
        data = json.loads(payload)
        print("{0}.value {1}".format(TICKER.lower(), data[6]))
