#!/usr/bin/env python3
import os.path
import sys
from urllib.request import urlopen

from bs4 import BeautifulSoup

import codecs

sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())

URL = "https://www.conseq.cz/penze/prehled-ucastnickych-fondu"
FUNDS = {
     "Conseq povinný konzervativní fond": "konz",
     "Conseq dluhopisový účastnický fond": "dl",
     "Conseq globální akciový účastnický fond": "glak",
}
ALIASES = {
    "CpsGLAK": "glak",
    "CpsKONZ": "konz",
    "CpsDL": "dl",
}


try:
    CMD = sys.argv[1]
except IndexError:
    CMD = "fetch"

if CMD == "config":
    print("host_name ticker")
    print("graph_title Conseq Pension")
    print("graph_args --base 1000")
    print("graph_scale no")
    print("graph_category ticker")
    print("graph_vlabel {0}".format("CZK"))
    for name, short in FUNDS.items():
        print("{0}.label {1}".format(short, name))
else:
    with urlopen(URL) as handle:
        payload = handle.read()

    html = BeautifulSoup(payload, "lxml")
    for row in html.find_all("table")[1].find_all("tr", class_="js-fund-row"):
        cells = row.find_all("td")
        name = cells[0].text
        price = cells[3].text.strip().split()[0].replace(",", ".")
        if name in FUNDS:
            key = FUNDS[name]
        else:
            key = ALIASES[name]
        print("{0}.value {1}".format(key, price))
