#!/usr/bin/env python3
import os.path
import sys
from urllib.request import urlopen

from bs4 import BeautifulSoup

import codecs

sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())

BASE = "https://www.conseq.cz/investice/prehled-fondu/{}"

NAME = os.path.basename(sys.argv[0]).replace("conseq_", "")
if not NAME:
    NAME = "conseq-invest-akcie-nove-evropy-a"

try:
    CMD = sys.argv[1]
except IndexError:
    CMD = "fetch"

with urlopen(BASE.format(NAME)) as handle:
    payload = handle.read()

html = BeautifulSoup(payload, "lxml")

name = html.h1.text
info_sec = html.find(class_="section__info__in")
isin = info_sec.find_all("dd")[0].text.strip()
price = float(
    info_sec
    .find_all("dd")[2]
    .text.strip()
    .split(')')[1]
    .split('\xa0')[0]
    .replace(",", ".")
)

if CMD == "config":
    print("host_name ticker")
    print("graph_title Conseq: {0}".format(name))
    print("graph_args --base 1000")
    print("graph_scale no")
    print("graph_category ticker")
    print("graph_vlabel {0}".format("CZK"))
    print("{0}.label {1}".format(isin.lower(), name))
else:
    print("{0}.value {1}".format(isin.lower(), price))
