#!/usr/bin/env python3
import os.path
import sys
from urllib.request import urlopen

from bs4 import BeautifulSoup

import codecs
sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())

BASE = 'https://www.conseq.cz/news_detail.asp?page=386&news={}'
FUNDS = (
    (
        'konz',
        866,
        'Conseq povinný konzervativní fond',
    ),
    (
        'dl',
        863,
        'Conseq dluhopisový účastnický fond'
    ),
    (
        'glak',
        862,
        'Conseq globální akciový účastnický fond',
    ),
)

# h2 is title
# #c40366-module-container span.large-font')[1] is price

try:
    CMD = sys.argv[1]
except IndexError:
    CMD = 'fetch'

if CMD == 'config':
    print('host_name ticker')
    print('graph_title Conseq Pension')
    print('graph_args --base 1000')
    print('graph_scale no')
    print('graph_category ticker')
    print('graph_vlabel {0}'.format('CZK'))


for short, num_id, name in FUNDS:
    if CMD == 'config':
        print('{0}.label {1}'.format(short, name))
    else:
        with urlopen(BASE.format(num_id)) as handle:
            payload = handle.read()

        html = BeautifulSoup(payload, 'lxml')

        price = float(
            html.find_all('table')[0].find_all('tr')[2].find_all('td')[4].text.strip().split()[0].replace(',', '.')
        )

        print('{0}.value {1}'.format(short, price))
