#!/usr/bin/env python3
import os.path
import sys
from urllib.request import urlopen

from bs4 import BeautifulSoup

import codecs

sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())

BASE = "https://www.ing.cz/podilove-fondy/nabidka-fondu/{0}/"

NAME = os.path.basename(sys.argv[0]).replace("ing_", "")
if not NAME:
    NAME = "ing-aria-lion-moderate"

# h1 is title
# #c40366-module-container span.large-font')[1] is price

try:
    CMD = sys.argv[1]
except IndexError:
    CMD = "fetch"

with urlopen(BASE.format(NAME)) as handle:
    payload = handle.read()

html = BeautifulSoup(payload, "lxml")

name = html.h2.text
price_text = html.find(class_="fundSmartDesc").find(class_="value").text.strip().split()
price = float(price_text[0].replace(",", "."))
currency = price_text[1]

if CMD == "config":
    print("host_name ticker")
    print("graph_title ING: {0}".format(name))
    print("graph_args --base 1000")
    print("graph_scale no")
    print("graph_category ticker")
    print("graph_vlabel {0}".format(currency))
    print("{0}.label {1}".format(NAME.lower(), name))
else:
    print("{0}.value {1}".format(NAME.lower(), price))
