#!/usr/bin/env python3
import os.path
import sys
from urllib.request import urlopen

from bs4 import BeautifulSoup

import codecs
sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())

BASE_1 = 'http://www.ingbank.cz/ing-podilove-fondy/nabidka-fondu/zakladni-nabidka-ing-podilovych-fondu-bez-poplatku/{0}/'
BASE_2 = 'http://www.ingbank.cz/ing-podilove-fondy/kompletni-nabidka-ing-podilovych-fondu/{0}/'
BASE_3 = 'http://www.ingbank.cz/ing-podilove-fondy/rozsirena-nabidka-podilovych-fondu/{0}.html'

BASIC = {
    'ing-aria-lion-moderate',
    'ing-aria-lion-balanced',
    'ing-aria-lion-dynamic',
    'ing-aria-lion-aggresive',
}

EXTENDED = {
    'franklin-global-convertible-securities',
    'fidelity-japan-advantage',
}

NAME = os.path.basename(sys.argv[0]).replace('ing_', '')
if not NAME:
    NAME = 'ing-aria-lion-moderate'

if NAME in BASIC:
    BASE = BASE_1
elif NAME in EXTENDED:
    BASE = BASE_3
else:
    BASE = BASE_2

# h1 is title
# #c40366-module-container span.large-font')[1] is price

try:
    CMD = sys.argv[1]
except IndexError:
    CMD = 'fetch'

with urlopen(BASE.format(NAME)) as handle:
    payload = handle.read()

html = BeautifulSoup(payload, 'lxml')

name = html.h1.text
price = float(
    html.find('table').find_all('tr')[1].td.text.strip().split()[0].replace(',', '.')
)

if CMD == 'config':
    print('host_name ticker')
    print('graph_title ING: {0}'.format(name))
    print('graph_args --base 1000')
    print('graph_scale no')
    print('graph_category ticker')
    print('graph_vlabel {0}'.format('CZK'))
    print('{0}.label {1}'.format(NAME.lower(), name))
else:
    print('{0}.value {1}'.format(NAME.lower(), price))
